name        : mupen64plus
version     : 2.5
release     : 2
source      :
    - https://github.com/mupen64plus/mupen64plus-core/releases/download/2.5/mupen64plus-core-src-2.5.tar.gz : 59e99a79e7f862517232e3115bd1f72377e3e34da795c118ba617c478c839578
    - https://github.com/mupen64plus/mupen64plus-audio-sdl/releases/download/2.5/mupen64plus-audio-sdl-src-2.5.tar.gz : 1c59f8c2d70206350c0b9067a9722cf2dd67e5686994d5a55adbf51ee8812f59
    - https://github.com/mupen64plus/mupen64plus-input-sdl/releases/download/2.5/mupen64plus-input-sdl-src-2.5.tar.gz : 65e528667b7f57a307b92abba37a3601ee17e9dd9d303ba7e4163b27f3ef771b
    - https://github.com/mupen64plus/mupen64plus-rsp-hle/releases/download/2.5/mupen64plus-rsp-hle-src-2.5.tar.gz : 4b2e11193746e0fbe4dfa78426c1214cf2e42779132eb2f668bf88f498517703
    - https://github.com/mupen64plus/mupen64plus-video-glide64mk2/releases/download/2.5/mupen64plus-video-glide64mk2-src-2.5.tar.gz : ef3dae0084e078d843605abdf5039eb8b5dd68ff1410b4fc12bdf19592a9fcb6
    - https://github.com/mupen64plus/mupen64plus-video-rice/releases/download/2.5/mupen64plus-video-rice-src-2.5.tar.gz : 969f65b9f42f48bc7e840e4ed1342233e4371c2edca5aa8f36f69c4b20955828
    - https://github.com/mupen64plus/mupen64plus-ui-console/releases/download/2.5/mupen64plus-ui-console-src-2.5.tar.gz : 71fee012678ff88f18130e339afd8c5467a2646b7e50da75ba2d5fa342b74a67
license     : GPL-2.0
component   : games.emulator
summary     : N64 emulator
description : |
    Mupen64Plus is a cross-platform plugin-based N64 emulator which is capable of accurately playing many games. Included are four MIPS R4300 CPU emulators, with dynamic recompilers for 32-bit x86 and 64-bit amd64 systems, and necessary plugins for audio, graphical rendering (RDP), signal co-processor (RSP), and input. There is 1 included OpenGL video plugin, called RiceVideo. There are 3 other excellent video plugins being maintained by wahrhaft, called Arachnoid, Glide64, and Z64.
builddeps   :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(samplerate)
    - pkgconfig(sdl2)
    - pkgconfig(speex)
    - libboost-devel
build      : |
    # Build core first.
    make -C projects/unix all PREFIX=/usr LIBDIR=%libdir%
    %make_install -C projects/unix PREFIX=/usr LIBDIR=%libdir%
    
    # Build the remaining plugins
    mkdir plugin_build
    pushd plugin_build
    for plugin in audio-sdl input-sdl rsp-hle video-glide64mk2 video-rice ui-console; do
        tar xvf $sources/mupen64plus-${plugin}-src-${version}.tar.gz
        pushd "mupen64plus-${plugin}-src-${version}"
        CFLAGS="$CFLAGS -I${installdir}/usr/include/mupen64plus" make -C projects/unix all PREFIX=/usr LIBDIR=%libdir% APIDIR="$installdir/usr/include"
        popd
    done
    popd
install    : |
    # Install all the plugins now
    pushd plugin_build
    for plugin in audio-sdl input-sdl rsp-hle video-glide64mk2 video-rice ui-console; do
        pushd "mupen64plus-${plugin}-src-${version}"
        %make_install -C projects/unix PREFIX=/usr LIBDIR=%libdir% APIDIR="$installdir/usr/include"
        popd
    done
    popd
