name       : mupen64plus
version    : '2.5'
release    : 14
source     :
    - https://github.com/mupen64plus/mupen64plus-core/releases/download/2.5/mupen64plus-bundle-src-2.5.tar.gz : 9c75b9d826f2d24666175f723a97369b3a6ee159b307f7cc876bbb4facdbba66
license    : GPL-2.0-only
component  : games.emulator
summary    : N64 emulator
description: |
    Mupen64Plus is a cross-platform plugin-based N64 emulator which is capable of accurately playing many games. Included are four MIPS R4300 CPU emulators, with dynamic recompilers for 32-bit x86 and 64-bit amd64 systems, and necessary plugins for audio, graphical rendering (RDP), signal co-processor (RSP), and input. There is 1 included OpenGL video plugin, called RiceVideo. There are 3 other excellent video plugins being maintained by wahrhaft, called Arachnoid, Glide64, and Z64.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(samplerate)
    - pkgconfig(sdl2)
    - pkgconfig(speex)
    - libboost-devel
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
    export LDFLAGS="${LDFLAGS},--allow-multiple-definition"
setup      : |
    %patch -p1 < $pkgfiles/010-mupen64plus-ui-console-pie.patch
build      : |
    ./m64p_build.sh
install    : |
    ./m64p_install.sh DESTDIR=$installdir PREFIX=/usr LIBDIR=%libdir% LDCONFIG=true
